### ISSUE TITLE
Feature request: Some type of dark mode

### ISSUE THREAD

**Issue by Huzwif2** [osem598/Firefox-98#1]
Basically the title if i mix and match with random Firefox vanilla themes i have i can get the colours looking better but a proper dark mode implementation would be awesome. Other than that this is perfect, thanks!

**Comment by osem598** [comment]
Yeah, i'll start tonight :). Also plan to fix colors in private browsing. Commits should be made by tomorrow night 👍 (i thank you for your kind words)

**Comment by osem598** [comment]
dark mode roughed in :) check colors.txt in the chrome directory to see how to do it

**Comment by Huzwif2** [comment]
Bro this is perfect ily thank u
________________________________
